import Head from 'next/head'
import Navbar from '../Components/Navbar'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import 'https://fonts.googleapis.com/css2?family=Manrope:wght@500&display=swap';

export default function Home() {
  return (
    <>
      <Head>
        <title>DaanaSetu</title>
        {/* <Link rel="preconnect" href="https://fonts.googleapis.com"></Link>
<Link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></Link>
<Link href="https://fonts.googleapis.com/css2?family=Manrope:wght@500&display=swap" rel="stylesheet"></Link> */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="icon.png" />
      </Head>
      <Navbar />
      <div className={styles.main}>
        <div className={styles.info}>
          <div className={styles.art1}>
           <Image src="/dilv.jpeg" width="440" height="270" className={styles.dilv}></Image>
          </div>
          <div className={styles.art2}>
            <h1>Welcome to DaanaSetu</h1><br></br>
            <h3>Your one step destination is to effectively donate items to our carefully curated, selected and verified orphanage and old age homes.</h3>
          </div>
        </div>
        <div className={styles.container}>
          <Link href="/Top_Donors" className={styles.context}>
            <div >
              <Image src="/topdonors.jpeg" width="165" height="90" className={styles.pic} alt=""></Image>
              <h3 className={styles.tex}>Top Donors</h3>
            </div>
          </Link>
          <Link href="/history" className={styles.context}>
            <div>
              <Image src="/history.jpeg" width="165" height="90" className={styles.pic} alt=""></Image>
              <h3 className={styles.tex}> History</h3>
            </div>
          </Link>
          <Link href="/Recieve" className={styles.context}>
            <div>
              <Image src="/own.jpeg" width="165" height="90" className={styles.pic} alt=""></Image>
              <h3 className={styles.tex}>Own a charity organisation?</h3>
            </div>
          </Link>
          <Link href="/donate" className={styles.donate}>
            <div>
              <Image src="/donation.jpeg" width="230" height="185" className={styles.picd} alt=""></Image>
              <h2 className={styles.textd}>Donate</h2>
            </div>
          </Link>
        </div>
        <div className={styles.footer}>
          {/* <a href="#" className="pp">Privacy Policy</a>
          <a href="#" className="tc">Terms & Conditions</a> */}
        </div>
      </div>
    </>
  )
}
